spring:
  application:
    name: trade-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO
    '[com.company.trade]': DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics